services:
  postgres:
    image: postgres:16
    container_name: course-service-postgres
    environment:
      POSTGRES_DB: nkbost-course-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2025!
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: