spring:
  application:
    name: course-service
  config:
    import: optional:configserver:http://configuser:configpass@localhost:8888/api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  zipkin:
    base-url: http://localhost:9411  # endereço do seu servidor Zipkin
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% das requisições vão ser coletadas e enviadas para o Zipkin

logging:
  level:
    org.springframework.cloud.config.client: DEBUG